import type { Metadata } from 'next';
import React from 'react';
import { inter } from '@/font';
import TranslationsProvider from '@/provider/TranslationProvider';
import PageLayout from '@/components/ui/drawer';
import Provider from './provider';
import initTranslations from '@/app/i18n';

import '@/style/globals.css';
import '@/style/main.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const i18Namespaces = ['lang'];

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { resources } = await initTranslations(locale, i18Namespaces);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <TranslationsProvider namespaces={i18Namespaces} resources={resources} locale={locale}>
            <PageLayout>{children}</PageLayout>
          </TranslationsProvider>
        </Provider>
      </body>
    </html>
  );
}
